name: Fetch News RSS to public/news.json
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # main へ push する権限

    steps:
      - uses: actions/checkout@v4   # main ブランチ

      - run: npm install rss-parser@^3.12.0

      - name: Convert RSS → JSON
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const Parser = require('rss-parser');
          const parser = new Parser();

          // 日本語クエリをエンコード
          const encoded = encodeURI(
            'https://news.google.com/rss/search?q=府中市&hl=ja&gl=JP&ceid=JP:ja'
          );

          (async () => {
            const feed = await parser.parseURL(encoded);
            const items = feed.items.map(({ title, link, pubDate }) => ({
              title, link, pubDate
            }));
            fs.mkdirSync('public', { recursive: true });
            fs.writeFileSync('public/news.json', JSON.stringify(items, null, 2));
          })();
          NODE

      - name: Commit & push
  env:
    GH_TOKEN: ${{ secrets.GH_BOT_PAT }}
  run: |
    git config --global user.email "bot@example.com"
    git config --global user.name  "news-bot"
    git pull --rebase origin main         # ★ 最新を取り込んで衝突回避
    git add public/news.json
    git commit -m "chore: update news feed" || echo "No changes"
    git push origin main                  # fast-forward OK
