name: Fetch News RSS to JSON
on:
  schedule:
    - cron: "*/10 * * * *"      # 10 分毎
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write            # gh-pages へ push するため

    steps:
      # 1. gh-pages ブランチを直接チェックアウト
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      # 2. rss-parser をインストール
      - name: Install rss-parser
        run: npm install rss-parser@^3.12.0

      # 3. Node スクリプトで RSS → news.json
      - name: Convert RSS to JSON
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const Parser = require('rss-parser');
          const parser = new Parser();
          (async () => {
            const feed = await parser.parseURL(
              'https://news.google.com/rss/search?q=府中市&hl=ja&gl=JP&ceid=JP:ja'
            );
            const items = feed.items.map(({ title, link, pubDate }) => ({
              title,
              link,
              pubDate,
            }));
            fs.writeFileSync('news.json', JSON.stringify(items, null, 2));
          })();
          NODE

      # 4. 変更があればコミット & push
      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_PAT }}
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name  "news-bot"
          git add news.json
          git commit -m "chore: update news feed" || echo "No changes"
          git push origin gh-pages
