name: Fetch News RSS to news.json
on:
  schedule:
    - cron: "*/10 * * * *"     # 10 分ごと
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # main へ push する権限

    steps:
      # 1) main ブランチをチェックアウト
      - uses: actions/checkout@v4

      # 2) rss-parser をインストール
      - name: Install rss-parser
        run: npm install rss-parser@^3.12.0

      # 3) RSS → JSON へ変換
      - name: Convert RSS to JSON
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const Parser = require('rss-parser');
          const parser = new Parser();
          (async () => {
            const feed = await parser.parseURL(encodeURI(
              'https://news.google.com/rss/search?q=府中市&hl=ja&gl=JP&ceid=JP:ja'
            ));
            const items = feed.items.map(({ title, link, pubDate }) => ({
              title, link, pubDate
            }));
            fs.writeFileSync('public/news.json', JSON.stringify(items, null, 2));
          })();
          NODE

      # 4) Git設定 & push
      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_PAT }}
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name  "news-bot"

          git add public/news.json
          git commit -m "chore: update news" || echo "No changes"
          git pull --rebase origin main
          git push origin main
